# IMPORTANT: The version must match the version of docker-compose.yml
---
version: '3.6'
services:
  # Your custom Docker image here:
  wireguard:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SERVERURL=<yoururl>.duckdns.org #optional
      - SERVERPORT=51820 #optional
      - PEERS=10 #optional
